/**
 * Agent control-channel wire-protocol schemas — Quick Task 260604-cwa.
 *
 * DEV-ONLY contracts shared by:
 *   - the bridge agent-registry + agent-routes (/debug/agent WS, /debug/agents,
 *     /debug/cmd, /debug/logs),
 *   - the g2-app installDebugAgent() client (debug-agent.ts).
 *
 * These models the privileged agent control channel that enables headless
 * end-to-end driving of the wizard pairing flow from an external orchestrator
 * (curl/ws) while reading aggregated bridge + g2-app logs via /debug/logs.
 *
 * # Security surface (T-cwa-01 … T-cwa-05)
 *
 * All new routes are registered ONLY inside the existing `isDebugEnabled()` block
 * in server.ts (existence gate — genuine 404 when off). Every HTTP route is
 * additionally guarded by `requireSecret` (timing-safe `EVF_INTERNAL_SECRET`).
 * The WS `/debug/agent` accepts `?secret=` because browsers cannot set WS headers.
 * Agent log events and command results flow through the SAME `DebugEventBus` whose
 * structural redaction scrubs known tokens.
 *
 * @see ./debug-events.ts (base DebugEvent schema + direction enum extended here)
 * @see packages/bridge/src/debug/agent-registry.ts (registry consumer)
 * @see packages/bridge/src/debug/agent-routes.ts (route consumer)
 * @see packages/g2-app/src/debug/debug-agent.ts (g2-app client)
 */
import { z } from 'zod';

// ─── Direction extensions ──────────────────────────────────────────────────────

/**
 * Direction value for agent log events pushed into the DebugEventBus.
 *
 * Extends the closed enum in {@link DebugEventSchema} additively — the bus
 * `byDirection()` seed also adds both new keys at 0 (see debug-event-bus.ts).
 */
export const DEBUG_AGENT_LOG_DIRECTION = 'agent-log' as const;

/**
 * Direction value for agent command results pushed into the DebugEventBus.
 *
 * Extends the closed enum in {@link DebugEventSchema} additively.
 */
export const DEBUG_AGENT_RESULT_DIRECTION = 'agent-result' as const;

// ─── Agent roles ───────────────────────────────────────────────────────────────

/** Valid agent roles for the debug control channel. */
export const AgentRoleSchema = z.enum(['g2-app', 'bridge', 'foundry']);
/** Valid agent roles (inferred). */
export type AgentRole = z.infer<typeof AgentRoleSchema>;

// ─── Agent register frame (client → bridge on WS open) ─────────────────────────

/**
 * Frame sent by a debug agent client immediately after WS connection to register
 * itself with the bridge agent registry.
 *
 * Fields:
 * - `kind`  — always `'register'` (discriminated union tag).
 * - `role`  — agent role (one of `g2-app | bridge | foundry`).
 * - `name`  — human-readable agent name (non-empty string, e.g. `'main'`).
 */
export const AgentRegisterSchema = z.object({
  /** Discriminated union tag. */
  kind: z.literal('register'),
  /** Agent role. */
  role: AgentRoleSchema,
  /** Human-readable agent name (non-empty). */
  name: z.string().min(1),
});
/** Agent register frame (inferred). */
export type AgentRegister = z.infer<typeof AgentRegisterSchema>;

// ─── Agent log frame (client → bridge, mirrored from console.*) ───────────────

/**
 * Log frame sent by a debug agent client to mirror `console.*` output to the bridge.
 *
 * Fields:
 * - `kind`   — always `'log'`.
 * - `ts`     — `Date.now()` ms epoch.
 * - `level`  — log level.
 * - `source` — originating module/function (free-form, e.g. `'wizard.ts'`).
 * - `msg`    — log message.
 */
export const AgentLogSchema = z.object({
  /** Discriminated union tag. */
  kind: z.literal('log'),
  /** `Date.now()` ms epoch. */
  ts: z.number().int(),
  /** Log level. */
  level: z.enum(['debug', 'info', 'warn', 'error']),
  /** Originating module/function (free-form). */
  source: z.string(),
  /** Log message. */
  msg: z.string(),
});
/** Agent log frame (inferred). */
export type AgentLog = z.infer<typeof AgentLogSchema>;

// ─── Agent command frame (bridge → client over WS) ────────────────────────────

/**
 * Command frame sent from the bridge to a connected agent over the WS control channel.
 * Dispatched by `POST /debug/cmd` via `AgentRegistry.send()`.
 *
 * Fields:
 * - `id`   — UUID v4 correlation id (generated by the registry).
 * - `cmd`  — command name (e.g. `'getState'`, `'setBridgeUrl'`).
 * - `args` — command-specific arguments (arbitrary object).
 */
export const AgentCommandSchema = z.object({
  /** UUID v4 correlation id generated by the registry. */
  id: z.string().uuid(),
  /** Command name (non-empty). */
  cmd: z.string().min(1),
  /** Command-specific arguments. */
  args: z.unknown(),
});
/** Agent command frame (inferred). */
export type AgentCommand = z.infer<typeof AgentCommandSchema>;

// ─── Agent result frame (client → bridge on WS, correlated by id) ─────────────

/**
 * Result frame sent by a debug agent client to report the outcome of a received command.
 * Correlated back to the originating `POST /debug/cmd` via the `id`.
 *
 * Fields:
 * - `kind`   — always `'result'`.
 * - `id`     — correlation id matching the dispatched command.
 * - `ok`     — `true` on success, `false` on error.
 * - `result` — optional result value (present when `ok: true`).
 * - `error`  — optional error message (present when `ok: false`).
 */
export const AgentResultSchema = z.object({
  /** Discriminated union tag. */
  kind: z.literal('result'),
  /** UUID v4 correlation id matching the dispatched command. */
  id: z.string().uuid(),
  /** Success flag. */
  ok: z.boolean(),
  /** Result value (present when ok: true). */
  result: z.unknown().optional(),
  /** Error message (present when ok: false). */
  error: z.string().optional(),
});
/** Agent result frame (inferred). */
export type AgentResult = z.infer<typeof AgentResultSchema>;

// ─── Client frame discriminated union ─────────────────────────────────────────

/**
 * Discriminated union of all frames sent FROM a debug agent client TO the bridge
 * over the `/debug/agent` WebSocket.
 *
 * The `kind` field is the discriminant:
 * - `'register'` — agent registration (first frame after open).
 * - `'log'`      — console.* mirror.
 * - `'result'`   — command result correlated by `id`.
 */
export const AgentClientFrameSchema = z.discriminatedUnion('kind', [
  AgentRegisterSchema,
  AgentLogSchema,
  AgentResultSchema,
]);
/** Discriminated union of all client→bridge frames (inferred). */
export type AgentClientFrame = z.infer<typeof AgentClientFrameSchema>;

// ─── POST /debug/cmd request body ─────────────────────────────────────────────

/**
 * Request body for `POST /debug/cmd` — relay a command to a named debug agent
 * and optionally wait for the result.
 *
 * Fields:
 * - `target` — agent name (or role fallback) to route the command to (non-empty).
 * - `cmd`    — command name (non-empty, e.g. `'setBridgeUrl'`).
 * - `args`   — command-specific arguments (arbitrary).
 * - `wait`   — when `true`, the bridge waits up to 2 s for the agent's result
 *              and includes it in the response.
 */
export const DebugCmdBodySchema = z.object({
  /** Agent name (or role) to route the command to. */
  target: z.string().min(1),
  /** Command name. */
  cmd: z.string().min(1),
  /** Command-specific arguments. */
  args: z.unknown(),
  /** When true, wait for the agent result and include it in the response. */
  wait: z.boolean().optional(),
});
/** Request body for `POST /debug/cmd` (inferred). */
export type DebugCmdBody = z.infer<typeof DebugCmdBodySchema>;
