/**
 * WS handshake message schemas — client → server and server → client.
 *
 * Matches the D-2.13 handshake protocol (02-CONTEXT.md § Decision C).
 * Sent once at WS connection open before any delta envelopes are exchanged.
 *
 * @see .planning/phases/02-foundry-module-core-pairing-ui/02-CONTEXT.md § D-2.13
 * @see docs/architecture/0002-protocol-versioning.md
 */
import { z } from 'zod';

/**
 * Client → Server handshake message.
 *
 * Sent as the first message after WS connection is established.
 * - `proto`        — Must be `"evf-v1"`.
 * - `token`        — Opaque 24h bearer (32-byte base64url, generated by Foundry module).
 * - `locale`       — BCP-47 primary tag (e.g. `"it"`, `"en"`).
 * - `capabilities` — Features the client claims to support.
 * - `session_id`   — Present on reconnect; omitted on first connect.
 * - `actorId`      — Optional selected PC actor id (bridge domain); when set the bridge
 *                    pins this session's `character.delta` to that actor so the HUD
 *                    renders the player's chosen PC instead of always `characters[0]`.
 *                    Must be non-empty when present (`min(1)`).
 *                    Omit entirely (not `""`) for back-compat with existing clients.
 */
export const HandshakeClientSchema = z.object({
  proto: z.literal('evf-v1'),
  token: z.string().min(1),
  locale: z.string().min(2).max(35),
  capabilities: z.array(z.string()),
  session_id: z.string().uuid().optional(),
  actorId: z.string().min(1).optional(),
});

export type HandshakeClient = z.infer<typeof HandshakeClientSchema>;

/**
 * Server → Client handshake response.
 *
 * Sent immediately after the server validates the client's handshake.
 * - `proto_chosen`   — Always `"evf-v1"` in Phase 2.
 * - `server_caps`    — Intersection of client capabilities and server-supported capabilities.
 * - `server_locale`  — Active locale (from Foundry `game.i18n.lang`, normalised to primary tag).
 * - `session_id`     — UUID v4 identifying this session. Client uses this for reconnect.
 * - `replay_seq`     — Last seq number in the replay buffer for this session.
 *                      `0` if this is a new session (no buffered deltas).
 */
export const HandshakeServerSchema = z.object({
  proto_chosen: z.literal('evf-v1'),
  server_caps: z.array(z.string()),
  server_locale: z.string().min(2).max(35),
  session_id: z.string().uuid(),
  replay_seq: z.number().int().nonnegative(),
});

export type HandshakeServer = z.infer<typeof HandshakeServerSchema>;

/**
 * All client capability strings supported by the server in Phase 2.
 *
 * "midiqol_capability_v1" is NOT in this list — it is only declared in Phase 7
 * when the MidiQOL write path is implemented (MIDIQ-01).
 */
export const SERVER_CAPS_V1 = ['read_char', 'read_combat', 'read_scene', 'subscribe'] as const;

export type ServerCap = (typeof SERVER_CAPS_V1)[number];
