/**
 * LogEvent Zod schema — Foundry chat log tail read shape.
 *
 * Maps Foundry `ChatMessage` documents (from `game.messages.contents`) to a
 * typed wire payload consumed by {@link LogPanel} in `packages/g2-app`.
 *
 * Produced by {@link packages/foundry-module/src/readers/log-reader.ts}.
 *
 * ## Event kinds
 *
 * | kind            | Foundry source                                 |
 * |-----------------|------------------------------------------------|
 * | `'attack'`      | `flags.dnd5e.roll.type === 'attack'`           |
 * | `'damage'`      | `flags.dnd5e.roll.type === 'damage'`           |
 * | `'spell'`       | `flags.dnd5e.use.type === 'spell'`             |
 * | `'feature'`     | `flags.dnd5e.use.type === 'feat'`              |
 * | `'round'`       | Synthetic — generated by combat-reader at round-advance |
 * | `'concentration'` | Concentration-related message                 |
 * | `'roll'`        | `flags.dnd5e.roll.type === 'save'`             |
 * | `'chat'`        | Fallback for unknown / plain-text messages     |
 *
 * **Assumption A4 (RESEARCH.md):** flag paths `flags.dnd5e.roll.type` and
 * `flags.dnd5e.use.type` are assumed from common dnd5e 5.x patterns. Verified
 * defensively at runtime — unknown flags default to `kind: 'chat'`.
 *
 * @see .planning/phases/05-panel-plugin-system-read-only-panels/05-05-PLAN.md
 * @see .planning/phases/05-panel-plugin-system-read-only-panels/05-UI-SPEC.md §5.9
 * @see .planning/phases/05-panel-plugin-system-read-only-panels/05-RESEARCH.md §Assumption A4
 * @see packages/foundry-module/src/readers/log-reader.ts (producer)
 * @see packages/g2-app/src/panels/log-panel.ts (consumer)
 */

import { z } from 'zod';

/**
 * Discriminated enum of log event kinds.
 *
 * Each kind drives a distinct icon + result rendering in {@link LogPanel}.
 * `'chat'` is the safe fallback for any unrecognised ChatMessage.
 */
export const LogEventKindSchema = z.enum([
  'attack',
  'damage',
  'spell',
  'feature',
  'round',
  'concentration',
  'roll',
  'chat',
]);

export type LogEventKind = z.infer<typeof LogEventKindSchema>;

/**
 * Optional sub-line data for a log event (roll result line).
 *
 * Rendered as an indented `→ <result>` row below the main log row.
 * Only present for events with a quantifiable outcome (attack hit/miss, save pass/fail).
 */
export const LogEventResultSchema = z.object({
  /** Outcome kind — drives the locale-resolved result label in `LogPanel`. */
  kind: z.enum(['hit', 'miss', 'pass', 'fail', 'concentrating']),
  /** Numeric total (attack roll total, save roll result, etc.). Optional. */
  value: z.number().int().optional(),
  /** Damage string for damage-roll events (e.g. `'12 taglio'`). Optional. */
  damage: z.string().optional(),
});

export type LogEventResult = z.infer<typeof LogEventResultSchema>;

/**
 * Single log event — one or two rows in the {@link LogPanel} tail.
 *
 * Fields are designed for direct rendering in `renderLogEvent()`:
 * - `actorName` truncated at 10 chars by the renderer (not here).
 * - `description` truncated at 40 chars by the renderer.
 * - `result` optional — when present produces the indented `→` sub-row.
 *
 * Uses `z.strictObject` to match the project convention for wire payloads
 * (unexpected fields are rejected at the parse boundary — T-05-05-01 mitigation).
 */
export const LogEventSchema = z.strictObject({
  /** Foundry ChatMessage document ID (stable across a session). */
  id: z.string().min(1),
  /**
   * Epoch timestamp (ms) of the ChatMessage.
   *
   * The renderer computes `T±HH:MM` relative to a caller-provided `nowEpoch`.
   */
  timestamp: z.number().int().nonnegative(),
  /** Speaker display name (from `message.speaker.alias`). Empty string if unavailable. */
  actorName: z.string(),
  /** Event kind — determines icon and result rendering. */
  kind: LogEventKindSchema,
  /** Human-readable event description (spell name, attack target, etc.). */
  description: z.string(),
  /** Optional result sub-line data (attack hit/miss, save pass/fail, etc.). */
  result: LogEventResultSchema.optional(),
});

export type LogEvent = z.infer<typeof LogEventSchema>;

/**
 * Envelope for a batch of log events (wire snapshot shape).
 *
 * Used by the bridge `log.delta` event channel.
 * Mirrors the `CombatSnapshotSchema` envelope shape for consistency.
 */
export const LogSnapshotSchema = z.strictObject({
  /** Ordered log events (oldest first within the tail window). */
  events: z.array(LogEventSchema),
});

export type LogSnapshot = z.infer<typeof LogSnapshotSchema>;

/**
 * `log.delta` wire type discriminator.
 *
 * Matches the `combat.turn` / `character.delta` convention — used as the
 * `type` field in the {@link @evf/shared-protocol#DeltaEnvelope} carrier.
 */
export const LOG_DELTA_TYPE = 'log.delta' as const;
